default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["DB_USERNAME"]%>
  password: <%= ENV["DB_PASSWORD"]%>

development:
  <<: *default
  database: db/aurora-development.postgresql

test:
  <<: *default
  database: db/aurora-test.postgresql

production:
  <<: *default
  database: db/aurora-production.postgresql
